DROP DATABASE IF EXISTS wifiserver;
CREATE DATABASE wifiserver;
USE wifiserver;

# Login
GRANT ALL PRIVILEGES ON wifiserver.* to server@'%.%.%.%' IDENTIFIED BY '123456';

# Msg
CREATE TABLE IF NOT EXISTS Msg (
	ID INTEGER UNSIGNED NOT NULL,
    Time TIMESTAMP NOT NULL,
    IP CHAR(16) NULL,
    Port INTEGER UNSIGNED NULL,
    mA FLOAT NULL,
    V FLOAT NULL,
    Hz FLOAT NULL,
    W FLOAT NULL,
    kWh FLOAT NULL,
	CONSTRAINT pk_msg PRIMARY KEY (ID, Time)
) ENGINE = InnoDB;
