DROP DATABASE IF EXISTS wifiserver;
CREATE DATABASE wifiserver;
USE wifiserver;

GRANT ALL PRIVILEGES ON wifiserver.* to server@'%.%.%.%' IDENTIFIED BY '123456';

CREATE TABLE IF NOT EXISTS Msg (
    czID INTEGER UNSIGNED NOT NULL,
    Time TIMESTAMP NOT NULL,
    IP CHAR(16) NULL,
    Port INTEGER UNSIGNED NULL,
    mA FLOAT NULL,
    V FLOAT NULL,
    Hz FLOAT NULL,
    W FLOAT NULL,
    kWh FLOAT NULL,
    CONSTRAINT pk_msg PRIMARY KEY (czID, Time)
) ENGINE = InnoDB;
