DROP DATABASE IF EXISTS shiep;
CREATE DATABASE shiep;
USE shiep;

# Login
GRANT ALL PRIVILEGES ON shiep.* to root@'10.%.%.%' IDENTIFIED BY 'sitemap';

# Msg
CREATE TABLE IF NOT EXISTS Msg (
	ID SMALLINT UNSIGNED NOT NULL,
	MTime TIMESTAMP NOT NULL,
	pID SMALLINT UNSIGNED NOT NULL,
	MTemp DECIMAL(4,2) NULL,
	MHum DECIMAL(4,2) NULL,
	MPhoto DECIMAL(4,2) NULL,
	MVoltage FLOAT NULL,
	MCurrent FLOAT NULL,
	MPower FLOAT NULL,
	MEnergy FLOAT NULL,
	MCount INTEGER UNSIGNED NULL,
	CONSTRAINT pk_msg PRIMARY KEY (ID, MTime)
) ENGINE = InnoDB;

