DROP DATABASE IF EXISTS server;
CREATE DATABASE IF NOT EXISTS server;

CREATE USER server@'localhost' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON server.* TO server@'localhost' WITH GRANT OPTION;
flush privileges;

USE server;
CREATE TABLE IF NOT EXISTS Msg (
    Time TIMESTAMP NOT NULL,
    IP CHAR(15) NOT NULL,
    Port SMALLINT UNSIGNED NOT NULL,
    mA DECIMAL(8,2) NOT NULL,
    V DECIMAL(8,2) NOT NULL,
    Hz DECIMAL(8,2) NOT NULL,
    W DECIMAL(8,2) NOT NULL,
    kWh DECIMAL(8,4) NOT NULL,
    CONSTRAINT pk_msg PRIMARY KEY (Time)
) ENGINE = InnoDB;
