DROP DATABASE IF EXISTS zigbee;
CREATE DATABASE zigbee;
USE zigbee;

# Login
GRANT ALL PRIVILEGES ON zigbee.* to root@'10.%.%.%' IDENTIFIED BY '123456';
GRANT SELECT,INSERT,UPDATE,DELETE ON zigbee.* to 'user'@'10.%.%.%' IDENTIFIED BY '';
GRANT SELECT ON zigbee.* to guest@'10.%.%.%' IDENTIFIED BY '';

# Msg
CREATE TABLE IF NOT EXISTS Msg (
	ID SMALLINT UNSIGNED NOT NULL,
	MTime TIMESTAMP NOT NULL,
	pID SMALLINT UNSIGNED NOT NULL,
	MTemp DECIMAL(4,2) NULL,
	MHum DECIMAL(4,2) NULL,
	MPhoto DECIMAL(4,2) NULL,
	MVoltage FLOAT NULL,
	MCurrent FLOAT NULL,
	MPower FLOAT NULL,
	MEnergy FLOAT NULL,
	MCount INTEGER UNSIGNED NULL,
	CONSTRAINT pk_msg PRIMARY KEY (ID, MTime)
) ENGINE = InnoDB;
CREATE VIEW MaxTime AS SELECT MAX(MTime) AS
	MTime,ID,pID,MTemp,MHum,MPhoto,MVoltage,MCurrent,MPower,MEnergy,MCount
	FROM Msg GROUP BY ID ORDER BY ID;

# zigbee_MapGIS
CREATE TABLE IF NOT EXISTS NodeGIS (
	NId SMALLINT UNSIGNED NOT NULL,
	NLon DECIMAL(12,9) NULL,
	NLat DECIMAL(12,9) NULL,
	CONSTRAINT pk_nodgis PRIMARY KEY (NId)
) ENGINE = InnoDB;

# pc_Overload
CREATE TABLE IF NOT EXISTS Overload (
	IP CHAR(15) NOT NULL,
	Class ENUM('Guide','Write','Read') NOT NULL,
	Time TIMESTAMP NOT NULL,
	CPU FLOAT UNSIGNED NULL,
	Mem FLOAT UNSIGNED NULL,
	MemAll CHAR(20) NULL,
	Disk FLOAT UNSIGNED NULL,
	DiskAll CHAR(20) NULL,
	RunTime CHAR(20) NULL,
	UsrNum SMALLINT UNSIGNED NULL,
	Avg01 FLOAT UNSIGNED NULL,
	Avg05 FLOAT UNSIGNED NULL,
	Avg15 FLOAT UNSIGNED NULL,
	CONSTRAINT pk_status PRIMARY KEY (IP)
) ENGINE = InnoDB;
INSERT INTO Overload (IP,Class) VALUES ("10.170.34.211",'Write');
INSERT INTO Overload (IP,Class) VALUES ("10.170.34.219",'Write');
INSERT INTO Overload (IP,Class) VALUES ("10.170.34.220",'Write');
